name: Python package

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
      - dev

jobs:


# specify a path
  uses: jpetrucciani/bandit-check@master
  with:
    path: '.'

  # provide some flags
  uses: jpetrucciani/bandit-check@master
  with:
    bandit_flags: '-lll -o output.json -f json'